import sys

debugmode='1'
diffdeposit='0'
sellpercentcheckbox='0'
sellpricecheckbox='0'
sellsecondscheckbox='0'
buypricecheck='0'
buytokenscheck='1'
selltokenscheck='0'
currency='GBP'
tradeaction='BUY'
tradepair='WBNB'
tokenstartprice=''
tokenbuyprice='300'
maxslippage='0.12'
diffdepositaddress=''
maxgwei='20'
gaslimit='500000'
tokenethaddress='0x78867BbEeF44f2326bF8DDd1941a4439382EF2A7'
tokenname='BUSD'
tokensymbol='BUSD'
tokendecimals='18'
sellmaxslippage=''
tokensellpercent=''
tokensellseconds=''
tokensellprice=''
ethamounttobuy='0.05'
tokensamounttobuy='10'
tokensamounttosell=''
infuraurl='https://data-seed-prebsc-1-s1.binance.org:8545/'
my_address = ''
my_pk = ''


sys.path.append(".")
