import sys

debugmode='1'
diffdeposit='0'
sellpercentcheckbox='0'
sellpricecheckbox='0'
sellsecondscheckbox='0'
buypricecheck='0'
buytokenscheck='0'
selltokenscheck='0'
forcesellcheck='1'
currency='GBP'
tradeaction='BUY/SELL'
tradepair='WBNB'
tokenstartprice=''
tokenbuyprice=''
maxslippage='0.12'
diffdepositaddress=''
maxgwei='20'
gaslimit='500000'
tokenethaddress='0x7ef95a0fee0dd31b22626fa2e10ee6a223f8a684'
tokenname='USDT'
tokensymbol='USDT'
tokendecimals='18'
sellmaxslippage=''
tokensellpercent=''
tokensellseconds=''
tokensellprice=''
tokenexactinput='0'
tokenexactoutput='0'
tokensellexactinput='0'
tokensellexactoutput='0'
tokenforcesellpercent='0.5'
infuraurl='https://data-seed-prebsc-1-s1.binance.org:8545/'
my_address = ''
my_pk = ''


sys.path.append(".")
